### ISSUE TITLE
Facial landmarks

### ISSUE THREAD

**Issue by sarmadm** [severin-lemaignan/gazr#1]
HI

Sorry may be it is not the right location to ask , but I couldn't find an answer for my question.
how the landmark points on the face such as the eyes can be  viewed ? e.g how to show the pixel locations of these landmarks ?

Thanks

**Comment by severin-lemaignan** [comment]
By simply enabling `DEBUG` from CMake, `gazr` will display a window with the position of the facial features on the 2D image.

You can see the code responsible for that here:
https://github.com/severin-lemaignan/gazr/blob/master/src/head_pose_estimation.cpp#L60

I'm closing the issue for now. Please re-open if this does not answer your question.

**Comment by sarmadm** [comment]
HI

Does this works on video file or webcam ? . What I meant is to get (x,y) points of landmarks for example 

using webcam to find eye corner  point(37).x , point(37).y  or any other points. Thanks

**Comment by severin-lemaignan** [comment]
Well, if you are only interesting in the position of the landmarks, then you might want to check directly the dlib documentation. This example, for instance, implements what you are looking for: http://dlib.net/face_landmark_detection_ex.cpp.html

You can as well use the gazr code as a starting point, put the position of the landmarks on the image is really what dlib does.

**Comment by sarmadm** [comment]
I have seen the dlib example , but when I use dlib I see it missing the facial point tracking sometimes and a little bit shaky , while gazr is more robust   . How can I use gazr to build an example like : face_landmark_detection_ex.cpp

**Comment by severin-lemaignan** [comment]
`gazr` is using `dlib` for face tracking. So it is exactly as robust as `dlib` ;-)

**Comment by sarmadm** [comment]
Hi is it possible to save facial landmarks (eye landmarks for example )

 into a file using show_head_pose.cpp ?

**Comment by severin-lemaignan** [comment]
The tool does not currently allows that, but you should be able to implement it rather easily.

Btw, please open different issues for different questions!
