### ISSUE TITLE
Yaw, roll and pitch angle

### ISSUE THREAD

**Issue by mwlodarczyk** [severin-lemaignan/gazr#10]
Hi,

I am trying to determine head yaw, roll and pitch angles using your solution. However, the results are very bad. I assume that the input parameters (e.g. focal length) are not set properly. 

Thus, I have the following questions: do you have any tips how to estimate the focal length for the webcam in my laptop? What steps should I take to adjust the algorithm for my data?

Hope you can help me.

Best,
Michal

**Comment by severin-lemaignan** [comment]
Hello @mwlodarczyk 

To compute yaw, pitch, raw, please refer to [this code sample](https://github.com/severin-lemaignan/gazr/blob/master/tools/estimate_head_direction.cpp#L128)

For the camera focal length, you probably want to check the [OpenCV's camera calibration tools](http://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html).

I'm closing the issue for now. Feel free to re-open if needed.
