### ISSUE TITLE
YPR range

### ISSUE THREAD

**Issue by srika91** [severin-lemaignan/gazr#11]
Hello Severin,
I have two questions.
What is the YPR range that can be obtained ?.Also did you test it with any standard dataset?

**Comment by severin-lemaignan** [comment]
@srika91 In our experience, +-40 deg horizontally and +- 30 deg vertically. You can find some details in [this paper](https://academia.skadge.org/publis/lemaignan2016realtime.pdf). 

I haven't tested it against standard datasets (that said, as far as I know, there isn't many datasets that provide face + ground truth of gaze's YPR -- I'm currently working on building a proper one)

**Comment by srika91** [comment]
Hey severin,
Thanks for the paper. You might be knowing,still there are two datasets we have come across BIWI kinect dataset and GI4E dataset.
