### ISSUE TITLE
ROS Kinetic dependencies are not working with gazr

### ISSUE THREAD

**Issue by mxochicale** [severin-lemaignan/gazr#12]
Having seen the ROS package dependencies at [CMakeLists.txt](https://github.com/severin-lemaignan/gazr/blob/master/CMakeLists.txt), I tried to install the following packages on ROS kinetic. However, it seems that gazr has been designed to work with another distribution for ROS because the following ones are not available for kinetic:
```
sudo apt-get install ros-kinetic-std_msgs
sudo apt-get install ros-kinetic-image_transport
sudo apt-get install ros-kinetic-image_geometry
sudo apt-get install ros-kinetic-cv_bridge
sudo apt-get install ros-kinetic-sensor_msgs
sudo apt-get install ros-kinetic-visualization_msgs
```
It would be good to add a description in the README.md for the ROS distribution which works with gazr. 

**NB.** For the time being, I am learning quite a lot from gazr, but if there is a way that I can contribute by having general instructions, I will happily give it a go to build the packages dependencies on ROS Kinetic.

**Comment by severin-lemaignan** [comment]
Hello,

Replace the underscores ('_') by dashes ('-') in your list of packages, and it should work :-)
But indeed, it would be useful to provide the list in the README. I'm happy to merge a pull-request!

**Comment by mxochicale** [comment]
Thanks, ros-kinetic dependencies have been installed successfully :)
```
sudo apt-get install ros-kinetic-roscpp ros-kinetic-tf ros-kinetic-std-msgs ros-kinetic-visualization-msgs ros-kinetic-sensor-msgs ros-kinetic-cv-bridge ros-kinetic-image-transport ros-kinetic-image-geometry
```
However, after gazr has been built the following errors appeared which I wouldn't be able to solve. Any recommendations? 

```
cmake -DWITH_ROS=ON -DDEBUG=ON  -DCMAKE_BUILD_TYPE=Release ..
```

```
/home/map479/gazr/src/ros_head_pose_estimator.cpp:109:44: error: ‘msg’ was not declared in this scope
         auto debugmsg = cv_bridge::CvImage(msg->header, "bgr8", estimator._debug).toImageMsg();
```

and with 

```
cmake -DWITH_ROS=ON -DDEBUG=OFF -DCMAKE_BUILD_TYPE=Release ..
```

```
/home/map479/gazr/tools/show_head_pose.cpp:100:38: error: ‘class HeadPoseEstimation’ has no member named ‘_debug’
         imshow("headpose", estimator._debug);
```

**Comment by j5207** [comment]
having the same problems.......have any solution yet?

**Comment by JamesGiller** [comment]
PR #18  should solve these issues.

**Comment by severin-lemaignan** [comment]
@mxochicale @j5207 I've merge PR #18, this should solve your issues. Can you try again? (you'd better delete your `build` directory, and start a new, clean build)
