### ISSUE TITLE
Can't find ros/ros.h

### ISSUE THREAD

**Issue by GeorgeMarkham** [severin-lemaignan/gazr#19]
Hi I'm having an issue where make displays the following error:
`gazr/src/head_pose_estimation.cpp:4:21: fatal error: ros/ros.h: No such file or directory`
This appears despite ROS being installed

**Comment by JamesGiller** [comment]
I responded to the same issue in #17

**Comment by severin-lemaignan** [comment]
@GeorgeMarkham if you pull the last version of `gazr`, ROS is enabled by default, and you should not have this issue anymore. I close the issue for now, feel free to re-open if you still have problems!
