### ISSUE TITLE
 Could not find a package configuration file provided by "dlib" 

### ISSUE THREAD

**Issue by sarmadm** [severin-lemaignan/gazr#2]
Hi 

 I have installed dlib and it works fine  , 

 when I cmake gazr this error is shown :

```
 ubuntu@ubuntu~/gazr/build$ cmake ..

CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake
```
can you help please to resolve this

**Comment by severin-lemaignan** [comment]
Well, you might need to tell CMake where you have installed CMake.
Something like:
```
$ cmake -Ddlib_DIR=<dlib install path>/lib/cmake/dlib ..
```
should do.

**Comment by sarmadm** [comment]
I used the command :


cmake -Ddlib_DIR=home/my_pc/dlib/lib/cmake/dlib ..

now I got this error :


CMake Error at /usr/lib/cmake/dlib/dlib.cmake:76 (message):
  The imported target "dlib::dlib" references the file

     "/usr/lib/libdlib.a"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/lib/cmake/dlib/dlib.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/lib/cmake/dlib/dlibConfig.cmake:35 (include)
  CMakeLists.txt:7 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/tofi/gazr/build/CMakeFiles/CMakeOutput.log".

**Comment by sarmadm** [comment]
I changed cmakelists these two lines : 

find_package(dlib REQUIRED)
include_directories(${dlib_INCLUDE_DIRS})

into 

set(DLIB_PATH "" CACHE PATH "Path to DLIB")
include(/home/tofi/dlib-19.0/dlib/cmake)

the cmake  ..   done without errors , but make shows this :


ubuntu@ubuntu:~/gazr/build$ make
[  3%] Built target gazr
[  4%] Linking CXX executable gazr_benchmark_head_pose_single_frame
CMakeFiles/gazr_benchmark_head_pose_single_frame.dir/tools/benchmark_head_pose_estimation_single_frame.cpp.o: In function `_GLOBAL__sub_I_main':
benchmark_head_pose_estimation_single_frame.cpp:(.text.startup+0x895): undefined reference to `USER_ERROR__missing_dlib_all_source_cpp_file__OR__inconsistent_use_of_DEBUG_or_ENABLE_ASSERTS_preprocessor_directives_'
libgazr.so: undefined reference to `dlib::base64::~base64()'
libgazr.so: undefined reference to `dlib::entropy_decoder_kernel_2::get_target(unsigned int)'
libgazr.so: undefined reference to `dlib::entropy_decoder_kernel_2::decode(unsigned int, unsigned int)'
libgazr.so: undefined reference to `dlib::entropy_decoder_kernel_2::~entropy_decoder_kernel_2()'
libgazr.so: undefined reference to `cblas_dgemm'
libgazr.so: undefined reference to `dlib::base64::decode(std::istream&, std::ostream&) const'
libgazr.so: undefined reference to `dgesvd_'
libgazr.so: undefined reference to `dlib::entropy_decoder_kernel_2::entropy_decoder_kernel_2()'
libgazr.so: undefined reference to `dlib::entropy_decoder_kernel_2::set_stream(std::istream&)'
libgazr.so: undefined reference to `dlib::base64::base64()'
collect2: error: ld returned 1 exit status
CMakeFiles/gazr_benchmark_head_pose_single_frame.dir/build.make:104: recipe for target 'gazr_benchmark_head_pose_single_frame' failed
make[2]: *** [gazr_benchmark_head_pose_single_frame] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/gazr_benchmark_head_pose_single_frame.dir/all' failed
make[1]: *** [CMakeFiles/gazr_benchmark_head_pose_single_frame.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sarmadm** [comment]
Hi , I'm using opencv 3.2 

I have got errors and I changed 

`#include <opencv2/highgui/highgui.hpp>`  to  `#include "opencv2/highgui.hpp"`  and  `#include <opencv2/imgproc/imgproc.hpp>`  to  `#include "opencv2/imgproc.hpp"`


and it comipled it successfuly , but when I try to execute this line 


`./head_pose_test ../share/shape_predictor_68_face_landmarks.dat`  it shows this error 

```
ubuntu@ubuntu:~/gazr/build$ ./head_pose_test ../share/shape_predictor_68_face_landmarks.dat

bash: ./head_pose_test: No such file or directory
```


here how I compile it 

```
ubuntu@ubuntu:~/gazr/build$ cmake -Ddlib_DIR=home/tofi/dlib/lib/cmake/dlib ..

-- Found OpenCV: /usr (found version "3.2.0") found components:  core imgproc calib3d highgui 
-- OpenCV version: 3.2.0
-- Found OpenCV: /usr (found version "3.2.0") found components:  core imgproc calib3d highgui imgcodecs videoio 
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tofi/gazr/build

ubuntu@ubuntu:~/gazr/build$ make
[ 25%] Built target gazr
[ 50%] Built target gazr_benchmark_head_pose_single_frame
[ 75%] Built target gazr_show_head_pose
[100%] Built target gazr_estimate_head_direction
ubuntu@ubuntu:~/gazr/build$ ./head_pose_test ../share/shape_predictor_68_face_landmarks.dat
bash: ./head_pose_test: No such file or directory
```

**Comment by severin-lemaignan** [comment]
Yes, as you can see from the compilation output, the name of test samples have changed.
You can try:
```
./gazr_show_head_pose ../share/shape_predictor_68_face_landmarks.dat
```
I'll update the README accordingly.
