### ISSUE TITLE
dlib link failure

### ISSUE THREAD

**Issue by takotakot** [severin-lemaignan/gazr#21]
Hi,

I encountered a compilation (link) problem with x86_64 environment:

```
cmake --version
cmake version 3.5.1

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
```

I built dlib with: 

```
cmake -DCMAKE_INSTALL_PREFIX:PATH=/home/takotakot/dlib_install/ -DBUILD_SHARED_LIBS=ON ..
make
make install
```

gazr with:

```
dlib_DIR=/home/takotakot/dlib_install/ cmake .. -DWITH_ROS=false
make
```

And get

```
/usr/bin/ld: /home/tako/dlib_install/lib/libdlib.a(base64_kernel_1.cpp.o): relocation R_X86_64_32S against `_ZTVN4dlib6base64E' can not be used when making a shared object; recompile with -fPIC
```

The content of `CMakeFiles/gazr.dir/link.txt` is 

```
/usr/bin/c++  -fPIC   -shared -Wl,-soname,libgazr.so -o libgazr.so CMakeFiles/gazr.dir/src/head_pose_estimation.cpp.o /home/takotakot/dlib_install/lib/libdlib.a /usr/local/lib/libopencv_calib3d.so.2.4.13 -lpthread -lnsl -lpng -lz -ljpeg /usr/local/lib/libopencv_features2d.so.2.4.13 /usr/local/lib/libopencv_flann.so.2.4.13 /usr/local/lib/libopencv_highgui.so.2.4.13 /usr/local/lib/libopencv_imgproc.so.2.4.13 /usr/local/lib/libopencv_core.so.2.4.13 -ldl -lm -lpthread -lrt -Wl,-rpath,/usr/local/lib
```

When I changed `/home/takotakot/dlib_install/lib/libdlib.a` to `/home/takotakot/dlib_install/lib/libdlib.so` manually, I could comiple libgazr.so .

Is this a gazr or cmake (or other tools) problem? If it could be fixed with changing some cmake configuration of gazr, I want to fix. But I'm sorry that I don't familiar with cmake.

Thanks

**Comment by severin-lemaignan** [comment]
It's a dlib issue, I believe. But if you are running ubuntu 16.04, you can simply `apt install libdlib-dev` and you're done!

**Comment by takotakot** [comment]
Thank you!

I wanted to build them myself, but I'll try `libdlib-dev` later. I'll report this issue to dlib.
