### ISSUE TITLE
Getting results in Gazr

### ISSUE THREAD

**Issue by MarcusFutterlieb** [severin-lemaignan/gazr#26]
So, everything is installed and working as best as I can tell. Here is what I got so far:

using the ROS node: 
`roslaunch gazr gazr.launch `
Output:
```
SUMMARY
========

PARAMETERS
 * /camera/gazr/face_model: /home/argos/catki...
 * /camera/gazr/prefix: face
 * /camera/gazr/with_depth: False
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    gazr (gazr/estimate)

auto-starting new master
process[master]: started with pid [9688]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e8951794-cd63-11e9-a309-a0a4c57336f1
process[rosout-1]: started with pid [9699]
started core service [/rosout]
process[camera/gazr-2]: started with pid [9705]
[ INFO] [1567416460.577348598]: Initializing the face detector with the model /home/argos/catkin_ws/src/gazr/shape_predictor_68_face_landmarks.dat...
[ INFO] [1567416462.437761834]: RGB-only estimator successfully initialized.
TF frames of detected faces will be published when detected,
as well as the nb of detected faces on /nb_detected_faces.
```

The camera is not turning on and if I check the rostopics, none of them are publishing.

-----------------------------------------------------------------------------------

If I try the stand alone tools:
`./gazr_show_head_pose ../../../../shape_predictor_68_face_landmarks.dat `
Output:
```
Corrupt JPEG data: 7 extraneous bytes before marker 0xd6
Processing time for this frame: 2252.85ms
```
I can see that the camera is turning on briefly, but apart from that nothing seems to be happening. 

Thanks for the the help,
Best
Marcus

**Comment by severin-lemaignan** [comment]
Closing old issue. Please re-open if problem persist and/or still relevant.
