### ISSUE TITLE
/home/tofi/gazr/tools/estimate_head_direction.cpp:71:5: error: ‘VideoCapture’ was not declared in this scope      VideoCapture video_in;      ^

### ISSUE THREAD

**Issue by sarmadm** [severin-lemaignan/gazr#3]
Hi , i'm getting this error during make :

I'm using opencv 3.1 is that causes this error ?

tofi@tofi:~/gazr/build$ make
Scanning dependencies of target gazr
[ 25%] Building CXX object CMakeFiles/gazr.dir/src/head_pose_estimation.cpp.o
Linking CXX shared library libgazr.so
[ 25%] Built target gazr
Scanning dependencies of target gazr_benchmark_head_pose_single_frame
[ 50%] Building CXX object CMakeFiles/gazr_benchmark_head_pose_single_frame.dir/tools/benchmark_head_pose_estimation_single_frame.cpp.o
Linking CXX executable gazr_benchmark_head_pose_single_frame
[ 50%] Built target gazr_benchmark_head_pose_single_frame
Scanning dependencies of target gazr_estimate_head_direction
[ 75%] Building CXX object CMakeFiles/gazr_estimate_head_direction.dir/tools/estimate_head_direction.cpp.o
/home/tofi/gazr/tools/estimate_head_direction.cpp: In function ‘int main(int, char**)’:
/home/tofi/gazr/tools/estimate_head_direction.cpp:71:5: error: ‘VideoCapture’ was not declared in this scope
     VideoCapture video_in;
     ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:71:18: error: expected ‘;’ before ‘video_in’
     VideoCapture video_in;
                  ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:74:9: error: ‘video_in’ was not declared in this scope
         video_in = VideoCapture(0);
         ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:77:22: error: ‘CV_CAP_PROP_FRAME_WIDTH’ was not declared in this scope
         video_in.set(CV_CAP_PROP_FRAME_WIDTH, 640);
                      ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:78:22: error: ‘CV_CAP_PROP_FRAME_HEIGHT’ was not declared in this scope
         video_in.set(CV_CAP_PROP_FRAME_HEIGHT, 480);
                      ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:105:23: error: ‘video_in’ was not declared in this scope
             auto ok = video_in.read(frame);
                       ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:149:48: error: ‘imshow’ was not declared in this scope
             imshow("headpose", estimator._debug);
                                                ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:151:27: error: ‘waitKey’ was not declared in this scope
                 waitKey(10);
                           ^
/home/tofi/gazr/tools/estimate_head_direction.cpp:154:33: error: ‘waitKey’ was not declared in this scope
                 while(waitKey(10) != 1048603) {}
                                 ^
make[2]: *** [CMakeFiles/gazr_estimate_head_direction.dir/tools/estimate_head_direction.cpp.o] Error 1
make[1]: *** [CMakeFiles/gazr_estimate_head_direction.dir/all] Error 2
make: *** [all] Error 2

**Comment by sarmadm** [comment]
could you please comment on this error

**Comment by skadge** [comment]
Could you tell me the output of `git log -1` (just to check what version of `gazr`  you are trying to compile)

**Comment by sarmadm** [comment]
tofi@tofi:~/gazr-master$ git log -1
fatal: Not a git repository (or any of the parent directories): .git

tofi@tofi:~/gazr-master/build$ git log -1
fatal: Not a git repository (or any of the parent directories): .git


I have downloaded gazr and compiled it , didn't use git just normal download from github

**Comment by skadge** [comment]
ok, indeed, I've been able to reproduce the issue. It should be fixed with the lastest commit.

Please re-open if you still encounter an issue.

**Comment by sarmadm** [comment]
It works now thanks very much

**Comment by sarmadm** [comment]
When I call `./gazr_show_head_pose ../share/shape_predictor_68_face_landmarks.dat`

tofi@tofi:~/gazr-master/build$ ./gazr_show_head_pose ../share/shape_predictor_68_face_landmarks.dat
init done 
opengl support available 
You must specify the path to a trained dlib's face model
with the option --model.
Segmentation fault (core dumped)

what is the correct procedure ?

**Comment by severin-lemaignan** [comment]
Well the error message is quite clear: add `--model` :-)
```
$ ./gazr_show_head_pose --model ../share/shape_predictor_68_face_landmarks.dat
```

**Comment by sarmadm** [comment]
The processing speed is very low ,the video from webcam is almost freeze .
what could be the reason ?

**Comment by skadge** [comment]
Check you've compiled both `dlib` and `gazr` in release mode. And please open different issues for different problems.
