### ISSUE TITLE
OpenBLAS library not found. 

### ISSUE THREAD

**Issue by ymohamed08** [severin-lemaignan/gazr#33]
whenever compling i get this error 

/usr/lib/x86_64-linux-gnu/libopenblas.so', needed by '/home/catkin_vis/devel/lib/libgazr.so'. 

and then i created a static link to the openblas library folder and then i got this error. 

ibdlib.a(base64_kernel_1.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN4dlib6base64E' can not be used when making a shared object; recompile with -fPIC 

is there a reason why it was not linked from the start? 

am using RTX3070 11.1 CUDA.

**Comment by severin-lemaignan** [comment]
You need to recompile `dlib` by hand, making sure `-fPIC` is passed to the compiler (should be by default, I believe)
