### ISSUE TITLE
What is the difference between this and attention tracker?

### ISSUE THREAD

**Issue by atv2016** [severin-lemaignan/gazr#4]
Any notable differences?
Thanks!

**Comment by skadge** [comment]
Hello!

`gazr` is the fork of `attention_tracker` that I'm still working on. No major changes (except maybe the 'WIP' branches with pupils tracking), but quite a few bugfixes.

**Comment by atv2016** [comment]
Hi Severin,
Ah! Understood. And bugfixes are always good, i will try yours out.
There was a bug (sort of) with a resolution of 1920x1080 (iMac) that would not display the yaw, roll,pitch properly (was a bit skewed). Let’s see if that’s fixed :-)

Also, will this in the future support gaze detection from the pupils (with a line showing on a heat map maybe where the user is looking?)

Thanks a lot,
Alef

On 6 Feb 2017, at 22:35, Séverin Lemaignan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!

gazr is the fork of attention_tracker that I'm still working on. No major changes (except maybe the 'WIP' branches with pupils tracking), but quite a few bugfixes.

**Comment by atv2016** [comment]
BTW, When i try to compile it like so i am getting the following message:
Zeus:build alefveld$ cmake -DDLIB_PATH=../dlib-18.18 ..
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:6 (find_package):
  By not providing "Finddlib.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "dlib", but
  CMake did not find one.

  Could not find a package configuration file provided by "dlib" with any of
  the following names:

    dlibConfig.cmake
    dlib-config.cmake

  Add the installation prefix of "dlib" to CMAKE_PREFIX_PATH or set
  "dlib_DIR" to a directory containing one of the above files.  If "dlib"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/Users/alefveld/Downloads/gazr-master/build/CMakeFiles/CMakeOutput.log”.

Any idea’s ?

On 6 Feb 2017, at 22:35, Séverin Lemaignan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello!

gazr is the fork of attention_tracker that I'm still working on. No major changes (except maybe the 'WIP' branches with pupils tracking), but quite a few bugfixes.

**Comment by skadge** [comment]
Yes: `dlib >= 18.18` provides a regular `dlibConfig.cmake` and (assuming `dlib` is installed on your system) can be found automatically by `CMake`, ie, no need to pass `-DDLIB_PATH`.

**Comment by atv2016** [comment]
I don’t usually have lib installed anywhere apart from local directories, is the find behaviour dependent on me installing it in, say /usr/local/include ?
On 6 Feb 2017, at 23:20, Séverin Lemaignan <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes: dlib >= 18.18 provides a regular dlibConfig.cmake and (assuming dlib is installed on your system) can be found automatically by CMake, ie, no need to pass -DDLIB_PATH.

**Comment by severin-lemaignan** [comment]
You might not need to install `dlib`: simply pointing `cmake` to `dlibConfig.cmake` in `dlib`'s `$BUILDDIR/config/` should be sufficient.

```
$ cmake -Ddlib_DIR=...
```
not tested though!

**Comment by severin-lemaignan** [comment]
Closing as inactive since a few month. Please re-open if needed!

**Comment by srika91** [comment]
Hey severin,
I still have this problem  of compiling.Can u tell where to find the $BUILDDIR/config/ ??

**Comment by severin-lemaignan** [comment]
@srika91 how have you installed `dlib`? if you simply follow the `gazr` installation instructions (ie, start with the pre-requisites: `sudo apt install libdlib-dev`), you should not have any trouble...

**Comment by srika91** [comment]
Hey severin,
I am using ubuntu 14.04 where libdlib-dev is not available and I have installed dlib 18.18 some time back and it is still running.
I am not able to figure the correct path to be supplied for cmake

**Comment by severin-lemaignan** [comment]
@srika91 ok, then the `$BUILDDIR` really depends on where you've downloaded/compiled/installed `dlib`. Just search on your machine for a file called `dlibConfig.cmake`, that should do.

**Comment by srika91** [comment]
I did try that like this,
cmake -Ddlib_DIR=home/srika91/Download/dlib-18.18/dlib/dlibConfig.cmake.in ..
I can find dlibConfig.cmake.in but not dlibConfig.cmake,am i missing something??

**Comment by srika91** [comment]
Just to add am using cmake version 3.2.2

**Comment by severin-lemaignan** [comment]
@srika91 yes, `dlibConfig.cmake.in` is the un-configured version. You need the one generated after the installatoin of `dlib` (ie `dlibConfig.cmake`). To be honest, these are general software engineering questions, not quite related to `gazr`. It would be helpful if you could find someone around you knowledgeable with `cmake` to help you. I do not really have time for that, sorry.

**Comment by srika91** [comment]
OK thanks for your help.I will check it out,i am new to cmake

**Comment by srika91** [comment]
Hey severin,

Can you point me to some resources where I can get the solution for this.

**Comment by srika91** [comment]
Hey severin,

I figured it out ,make install the dlib library is important which i missed.
