### ISSUE TITLE
webcam video is very slow

### ISSUE THREAD

**Issue by sarmadm** [severin-lemaignan/gazr#5]
I have compiled both dlib and gazr in release mode : 

> 
> mkdir build
> cd build
> cmake ..
> cmake --build . --config Release

but when I run 

> ./gazr_show_head_pose --model ../share/shape_predictor_68_face_landmarks.dat

the video from webcam is very slow

**Comment by severin-lemaignan** [comment]
To compile in release mode, you would typically compile project like that:

```
$ mkdir build
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make
```

**Comment by sarmadm** [comment]
Thanks , it is solved now
