### ISSUE TITLE
Can you recommend a camera to get reliable data for multiple user gaze estimation?

### ISSUE THREAD

**Issue by mxochicale** [severin-lemaignan/gazr#7]
Hiya,

I am not really sure whether this is the place to post this question, if not, please let me know! 

Having said that, I want to mention that I like what you are doing with gazr that I will denitifely work with your project for multiple user gaze estimation to which I am wondering which brand of web cam do you recomend to work with gazr? Also, what is the maximum number of users that gazr can estimate? 

Cheerio,
Miguel

**Comment by severin-lemaignan** [comment]
To be honest, the webcam does not really matter... dlib (the underlying library used by gazr) will be happy even with relatively poor images.

If you want to track multiple persons, you might need a wide enough angle, tough.

In terms of how many people can be tracked, there is not limit, except in term of CPU horsepower. You will need to try to see how many your machine is able to handle relative to your time constraints.

I close the issue for now, but feel free to further comment if needed!
