### ISSUE TITLE
./gazr_show_head_pose ... is not working properly 

### ISSUE THREAD

**Issue by mxochicale** [severin-lemaignan/gazr#8]
gazr has been successfully built with dlib-19.4 on Ubuntu 14.04 x64 with OpenCV version: 3.2.0 and Boost version: 1.54. For building dlib-19.4, it has been used "sudo cmake --build . --target install" 

Then, I try to test gazr as suggested
```
$ ./gazr_show_head_pose --model ../share/shape_predictor_68_face_landmarks.dat  
Setting the optical center to (320, 240)  
Processing time for this frame: 3464.05ms  
```
However, it only generates the previous two lines and I can also observe a quick
view of the window for a very short time.

I did another test with gazr_estimate_head_direction and live_plot.py with
```
$ ./gazr_estimate_head_direction --model=../share/shape_predictor_68_face_landmarks.dat | python -u ../tools/live_plot.py
```
It seems to be working since the traces of Pitch Yaw Roll changed over time when
the webcam is pointing my face but the processing is very slowly. 

I reckon, I am missing something to make it work. Do you have any comments?

P.S. "./webcam_face_pose_ex" in "~/dlib/dlib-19.4/examples/build" is working fine.

#### Machine Features 

Webcam
```
$ lsusb
Bus 002 Device 010: ID 046d:0991 Logitech, Inc. QuickCam Pro for Notebooks
```

Machine 
```
$ less /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i5 CPU         650  @ 3.20GHz
stepping        : 2
microcode       : 0xc
cpu MHz         : 1197.000
```
```
$ lshw -class memory
WARNING: you should run this program as super-user.
  *-memory                
       description: System memory
       physical id: 0
       size: 3751MiB
```

I appreciate your time and help.

**Comment by severin-lemaignan** [comment]
What you are probably missing is compilation in release mode: try `cmake -DCMAKE_BUILD_TYPE=Release .`

**Comment by mxochicale** [comment]
The good news is that after "cmake -DCMAKE_BUILD_TYPE=Release .." the professing speed has been improved when I use
```
./gazr_estimate_head_direction --model=../share/shape_predictor_68_face_landmarks.dat | python -u ../tools/live_plot.py
```
However, I am still observing the same behavior of viewing the webcam's window for a very short time.
My guess is that there is a problem with the WebCam configuration.
I will try to use another camera and also play around with
the values of FRAME_WIDTHFRAME_WIDTH and CV_CAP_PROP_FRAME_HEIGHT.

I will keep updating the issue. Thanks for your help.

**Comment by severin-lemaignan** [comment]
Any update? Can we close the issue?

**Comment by mxochicale** [comment]
gazr has successfully been built on a machine with Ubuntu 16.04 x64. However, I am still observing the same behavior of viewing the webcam's window for a very short time.
```
 ./gazr_show_head_pose --model ../share/shape_predictor_68_face_landmarks.dat  
Setting the optical center to (320, 240)
Processing time for this frame: 134.673ms
```
I have to say that the gazr_estimate_head_direction and live_plot.py is working fine. Let me share the terminal output when building gazr on Ubuntu 16.04: https://github.com/mxochicale/dlib/blob/master/gazr.md#on-ubuntu-1604-x64 

This time, I am using logitech "HD Webcam C270" with the default source code. I haven't done any modifications to the this variables which I guess it might work FRAME_WIDTHFRAME_WIDTH and CV_CAP_PROP_FRAME_HEIGHT. 

Any suggestion?

**Comment by adrey** [comment]
I've replaced `if (waitKey(10) >= 0) break;` with `if (waitKey(10) == 27) break;` in tools/show_head_pose.cpp, it helped

**Comment by mxochicale** [comment]
"./gazr_show_head_pose --model ../share/shape_predictor_68_face_landmarks.dat" is working after  following @adrey 's [suggestion](https://github.com/severin-lemaignan/gazr/issues/8#issuecomment-318597046). @severin-lemaignan, you can close this issue. Thank you!
