### ISSUE TITLE
Dependencies issues with dlibConfig.cmake when building gazr using dlib-19.4 in Release mode

### ISSUE THREAD

**Issue by mxochicale** [severin-lemaignan/gazr#9]
I am trying to build dlib-19.4 in release mode to increase the processing
speed using "cmake --build . --config Release" but I have been facing the following dependencies
issues with dlibConfig.cmake:

```
$ cmake -Ddlib_DIR=/home/map479-admin/dlib/dlib-19.4/build/dlib/config ..
.
.
.
CMake Error at /home/map479-admin/dlib/dlib-19.4/build/dlib/config/dlibConfig.cmake:35 (include):
  include could not find load file:

    /home/map479-admin/dlib/dlib-19.4/build/dlib/config/dlib.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)


CMake Error at /home/map479-admin/dlib/dlib-19.4/build/dlib/config/dlibConfig.cmake:42 (include):
  include could not find load file:

    /home/map479-admin/dlib/dlib-19.4/include/dlib/cmake_utils/use_cpp_11.cmake
Call Stack (most recent call first):
  CMakeLists.txt:11 (find_package)
```

To solve the previous problem I installed  dlib-19.4 with
"sudo cmake --build . --target install" which is not the release mode.

However, I want to install both dlib and gazr in release mode.

Do you have any suggestions?

**Comment by severin-lemaignan** [comment]
Well, if you encounter issues with compiling and installing `dlib` in release mode, you should probably open an issue with `dlib`.

That said, why aren't you using the debian/ubuntu `libdlib-dev` package?

**Comment by mxochicale** [comment]
I have tried to install libdlib-dev on Ubuntu 14.04 LTS, it seems that [libdlib-dev is not available for Ubuntu 14.04 LTS](https://askubuntu.com/questions/847090/ubuntu-14-04-lts-need-ppa-for-libdlib-dev)

I will upgrade my machine to Ubuntu16.04 LTS. Once upgraded I will test it and update this issue.

Thanks for your help

**Comment by severin-lemaignan** [comment]
Any update? Can we close the issue?

**Comment by mxochicale** [comment]
[I have posted some tests on Ubuntu 16.04x64 ](https://github.com/severin-lemaignan/gazr/issues/8#issuecomment-302751096) for which gazr is partially working.
Close this one.

**Comment by mxochicale** [comment]
You can close this issue as gazr is working now with [dlib.19.4.99 on Ubuntu 16.04x64.](https://github.com/mxochicale/dlib/blob/master/INSTALLATION_Ubuntu16.04.md)
